/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package swingjdbc;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author utsav
 */
public class districtt extends javax.swing.JFrame {
 Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
    /**
     * Creates new form districtt
     */
    public districtt() {
        initComponents();
        setLocation((screen.width - 400) / 2, (screen.height - 230) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Naubise = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Jiwanpur = new javax.swing.JButton();
        Gajuri = new javax.swing.JButton();
        Tipling = new javax.swing.JButton();
        Chhetre = new javax.swing.JButton();
        Lapa = new javax.swing.JButton();
        Maidi = new javax.swing.JButton();
        Benighat = new javax.swing.JButton();
        Chainpur = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Naubise.setText("Naubise");
        Naubise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaubiseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 92, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        Jiwanpur.setText("Jiwanpur");
        Jiwanpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JiwanpurActionPerformed(evt);
            }
        });

        Gajuri.setText("Gajuri");
        Gajuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GajuriActionPerformed(evt);
            }
        });

        Tipling.setText("Tipling");
        Tipling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TiplingActionPerformed(evt);
            }
        });

        Chhetre.setText("Chhetre");
        Chhetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChhetreActionPerformed(evt);
            }
        });

        Lapa.setText("Lapa");
        Lapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapaActionPerformed(evt);
            }
        });

        Maidi.setText("Maidi");
        Maidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaidiActionPerformed(evt);
            }
        });

        Benighat.setText("Benighat");
        Benighat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BenighatActionPerformed(evt);
            }
        });

        Chainpur.setText("Chainpur");
        Chainpur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChainpurActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Tipling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Naubise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jiwanpur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Gajuri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel)
                    .addComponent(Chhetre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Benighat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Chainpur)
                    .addComponent(Maidi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lapa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Naubise)
                    .addComponent(Lapa))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jiwanpur)
                            .addComponent(Maidi))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gajuri)
                            .addComponent(Benighat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Chhetre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipling)
                    .addComponent(Chainpur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cancel)
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NaubiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaubiseActionPerformed
    new AddNewProduct1(this, true).show();
        
       // new tablenaubise().setVisible(true);
    }//GEN-LAST:event_NaubiseActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
      new one1().show();
      new SplashScreen().show();
        this.dispose();
       
    }//GEN-LAST:event_cancelActionPerformed

    private void GajuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GajuriActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_GajuriActionPerformed

    private void JiwanpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JiwanpurActionPerformed
       new AddNewProduct1(this, true).show(); // TODO add your handling code here:
    }//GEN-LAST:event_JiwanpurActionPerformed

    private void TiplingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TiplingActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_TiplingActionPerformed

    private void ChhetreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChhetreActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_ChhetreActionPerformed

    private void ChainpurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChainpurActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_ChainpurActionPerformed

    private void LapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapaActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_LapaActionPerformed

    private void MaidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaidiActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_MaidiActionPerformed

    private void BenighatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BenighatActionPerformed
new AddNewProduct1(this, true).show();        // TODO add your handling code here:
    }//GEN-LAST:event_BenighatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(districtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(districtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(districtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(districtt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new districtt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Benighat;
    public javax.swing.JButton Chainpur;
    public javax.swing.JButton Chhetre;
    public javax.swing.JButton Gajuri;
    public javax.swing.JButton Jiwanpur;
    public javax.swing.JButton Lapa;
    public javax.swing.JButton Maidi;
    public javax.swing.JButton Naubise;
    public javax.swing.JButton Tipling;
    public javax.swing.JButton cancel;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
